### ISSUE TITLE
Avoid proxy loop

### ISSUE THREAD

**Issue by n2N8Z** [tinyproxy/tinyproxy#203] opened 2018-10-17 11:19 UTC
If I make a HTTP request to the proxy port, the proxy starts looping and eventually uses up all available connections, and stops serving requests.

e.g. curl http://proxy:8888

I know I can avoid this issue by setting StatHost to the proxy IP or hostname, and I can filter out the other domains that resolve to the proxy itself, but is that the recommended way to avoid the proxy loop ?

I haven't found any references to this issue related to Tinyproxy, and am surprised Tinyproxy does not avoid this issue by default.

I found the [same issue reported for squignix](https://github.com/tianon/squignix/issues/1), which they have apparently handled by not forwarding traffic that already included the proxy header.

**Comment by ryanc** [comment] 2019-07-10 18:23
I discovered this issue last night when our regular Nessus scan ran.

**Comment by rofl0r** [comment] 2019-07-10 22:25
duplicate of #199. see my answer there:
https://github.com/tinyproxy/tinyproxy/issues/199#issuecomment-450696448

**Closed by rofl0r** 2019-07-10 22:25 UTC

**Comment by n2N8Z** [comment] 2019-07-12 20:36
Yes, now it's a duplicate, but the fact that #199 was caused by a proxy loop was only discovered a full month (https://github.com/tinyproxy/tinyproxy/issues/199#issuecomment-440703812) after I posted this issue.

**Comment by n2N8Z** [comment] 2019-07-12 20:37
I've briefly tested the proxy loop fix - looks good.
Thanks for the fix.
