### ISSUE TITLE
build fail on centos7.1 

### ISSUE THREAD

**Issue by StevenChina** [tinyproxy/tinyproxy#186] opened 2018-08-15 04:52 UTC
fail msg :
Making all in man5
make[3]: Entering directory `/root/tinyproxy/docs/man5'
*** a2x (asciidoc) is required to regenerate tinyproxy.conf.5 ***
make[3]: *** [tinyproxy.conf.5] Error 1
make[3]: Leaving directory `/root/tinyproxy/docs/man5'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/root/tinyproxy/docs'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/tinyproxy'
make: *** [all] Error 2

I have installed asciidoc 
but it happened again , how to solve it ?

**Comment by rofl0r** [comment] 2018-08-16 12:57
yet another user troubled by the gratuitous dependency on `a2x`. how many more times this went unreported and left potentially thousands of users frustrated ?

duplicate of
#111
#2
#33
https://github.com/tinyproxy/tinyproxy/issues/182#issue-343855343
https://github.com/tinyproxy/tinyproxy/issues/72#issuecomment-327732512

**Comment by rofl0r** [comment] 2018-09-01 02:54
you can now use the release tarball from https://github.com/tinyproxy/tinyproxy/releases/tag/1.10.0 which contains the pregenerated manpage, so it builds without installed a2x

**Closed** 2018-09-01 02:54 UTC
