### ISSUE TITLE
Tinyproxy uses wrong client address for ACL checks when getting mixed IPv4 / IPv6 requests

### ISSUE THREAD

**Issue by juhassi** [tinyproxy/tinyproxy#495] opened 2023-05-31 06:13 UTC
Hi,

(first of all, apologies if this issue is already known or it's caused by something in our configuration)

We found a rather interesting issue in Ubuntu 22.04's tinyproxy package (version 1.11.0-1).

We have a setup where tinyproxy is used as a proxy allowing some servers in the internal network to access some pre-approved outside addresses. For this, we have Allow ACL's ("Allow 1.2.3.4", "Allow 1111:2222:3333:4444::42", etc) and a Filter file.

This used to work perfectly with Ubuntu 20.04 (which had Tinyproxy version 1.10.0-4).

I did a Ubuntu release upgrade to 22.04 (and Tinyproxy 1.11.0) and since then, I noticed that some requests to Tinyproxy where failing. The interesting bit was that these failed requests were logged as coming from IPv6 addresses that do not exist in the network.

After some head scratching, it seems like tinyproxy gets confused when it gets requests from both ipv4 and ipv6 hosts. Namely, the first proxied http:// request with different protocol seems to fail because tinyproxy uses incorrect (nonexistent) ipv6 address for ACL checks.

We found this was easily repeatable in our setup by manually running apt update in turn on two different hosts, both which were using tinyproxy to access the repositories; host1 was using ipv4 and host2 was using ipv6. For both hosts, first request got a 403 (and tinyproxy logged "Unauthorized connection from xx:xx"), all others worked.

It should be noted that our ACL's list full IPv4 and IPv6 addresses, we generally don't use masks for ACL's. Since only the last 32 bits of the logged IPv6 address were incorrect, having ACL's with masks would still let these requests thru.

**Comment by rofl0r** [comment] 2023-05-31 08:53
> The interesting bit was that these failed requests were logged as coming from IPv6 addresses that do not exist in the network.

then the question is whether tinyproxy is wrong here or your network setup. can you do a test where you have tcpdump running while getting such a request ? then you can transfer the pcap file to a machine with wireshark and check whether the ip addresses were really wrong.

> having ACL's with masks would still let these requests thru.

the ACL directives do indeed support masks.

**Comment by juhassi** [comment] 2023-05-31 09:10
I debugged this with tcpdump, watching only for SYN packets and the IPs were correct (both IPv4 and IPv6) on the wire. Did not save a pcap, tho.

Also, this issue was temporarily "fixed" by downgrading tinyproxy packages to Ubuntu 20.04's versions (1.10.0) while otherwise keeping the OS (and client) configurations intact. IMO would strongly suggest it's a problem in Tinyproxy that appeared between 1.10.0 and 1.11.0.

**Comment by rofl0r** [comment] 2023-06-01 13:36
> the IPs were correct (both IPv4 and IPv6) on the wire

and displayed wrongly in tinyproxy ? then it's probably a case where stuff wasnt fully initialized.

> this would strongly suggest it's a problem in Tinyproxy that appeared between 1.10.0 and 1.11.0.

it's possible. would you mind doing a git bisect between those 2 versions ? it would require approximately 5-6 builds to find the commit that introduced the bug. but then, maybe it's already fixed in latest git, you might wanna try that first.

**Comment by juhassi** [comment] 2023-06-02 08:49
Hi again,


Your proposed fix didn't seem to work - here's a tcpdump of 3 syn packets in a row:

```
08:35:56.151282 IP6 6001:1234::a:b:c:d.34814 > 6001:1234::a:b:c:d.3142: Flags [S], seq 831596171, win 65476, options [mss 65476,sackOK,TS val 4019857356 ecr 0,nop,wscale 7], length 0
08:35:58.983797 IP 192.168.1.22.34088 > 192.168.1.22.3142: Flags [S], seq 2068239194, win 65495, options [mss 65495,sackOK,TS val 1146380779 ecr 0,nop,wscale 7], length 0
08:36:00.983882 IP6 6001:1234::1.58108 > 6001:1234::1.3142: Flags [S], seq 2435103415, win 65476, options [mss 65476,sackOK,TS val 3621242974 ecr 0,nop,wscale 7], length 0
```

And this is how Tinyproxy saw those 3 connections:

```
Jun  2 08:35:56 tinyproxy-test1 tinyproxy[5275]: Connect (file descriptor 3): 6001:1234::a:b:c:d
Jun  2 08:35:58 tinyproxy-test1 tinyproxy[5275]: Connect (file descriptor 3): 192.168.1.22
Jun  2 08:36:00 tinyproxy-test1 tinyproxy[5275]: Connect (file descriptor 3): 6001:1234::a:b:c:d <-- wrong
```

I created a new test setup for this; a fresh Ubuntu 22.04 virtual machine that has tinyproxy (compiled from 1.11.1 + your fix to src/acl.c). This machine has several ip addresses and I'm using multiple ssh connections with http_proxy set differently to trigger http requests with wget.

One shell has `export http_proxy="http://[6001:1234::1]:3142/"` , another one has `export http_proxy="http://[6001:1234::a:b:c:d]:3142/"` and 3rd one has `export http_proxy="http://192.168.1.22:3142/"`

```
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 8950 qdisc fq_codel state UP group default qlen 1000
    link/ether fa:16:3e:3b:aa:20 brd ff:ff:ff:ff:ff:ff
    altname enp0s3
    inet 192.168.1.22/24 metric 100 brd 192.168.1.255 scope global dynamic ens3
       valid_lft 84682sec preferred_lft 84682sec
    inet6 7001:4321::1/64 scope global
       valid_lft forever preferred_lft forever
    inet6 6001:1234::a:b:c:d/64 scope global
       valid_lft forever preferred_lft forever
    inet6 6001:1234::1/64 scope global
       valid_lft forever preferred_lft forever
```

**Comment by rofl0r** [comment] 2023-06-03 11:34
> 6001:1234::a:b:c:d <-- wrong

not sure whether this is really wrong, it's one of the ipv6 addresses you designated to your interface, it might just take precedence in userspace. in your initial report you mentioned it would use non-existing ipv6 addresses, which led me to believe that some sort of memory corruption (or use of uninitialized memory) could be going on.
in order to get this fixed i'd recommend to either git bisect between 1.10 and 1.11 tags, or compiling latest git with address sanitizers enabled `CC="gcc -fsanitize=address" ./configure ...` or both. i noticed you used 1.11.1 tarball rather than git, presumably because git doesn't ship the configure script - you can produce it with `autoreconf -i`

**Comment by juhassi** [comment] 2023-06-07 08:19
Hi,

It's definitively wrong, the connection should be seen by tinyproxy as coming from the address which is shown in the tcpdump.

I did bit more testing, this time with batches of 1000 requests (for i in seq 1 1000) triggered from 1-3 terminals (with differing http_proxy variables). These summaries are done with `fgrep Connect tinyproxy.log | awk '{print $1 " " $10}' | sort | uniq -c`:

1.11.1 + patch (no -fsanitize=address), only one client address:
```
   1000 CONNECT 6001:1234::a:b:c:d
```

1.11.1 + patch (no -fsanitize=address), two client addresses (ipv4 + ipv4):
```
   1000 CONNECT 127.0.0.1
   1000 CONNECT 192.168.1.22
```

1.11.1 + patch (with address sanitization), two client addresses (ipv6 + ipv6):
```
   1000 CONNECT 6001:1234::1
   1000 CONNECT 6001:1234::a:b:c:d
```

Ok. So all of these seem to work - ipv4-only with 2 hosts, ipv6-only with 2 hosts (and ipv6-only with one host). From now on, this is where it gets interesting:

1.11.1 + patch (with address sanitization), two client addresses (ipv4 + ipv6):
```
   1000 CONNECT 192.168.1.22
     71 CONNECT 6001:1234::a:b:c:d
    929 CONNECT 6001:1234::b43f:7da1:ff0f:0
```    

1.11.1 + patch (no -fsanitize=address), three client addresses (ipv4 + ipv6 + ipv6):
```
   1000 CONNECT 192.168.1.22
      8 CONNECT 6001:1234::
   1197 CONNECT 6001:1234::1
    795 CONNECT 6001:1234::a:b:c:d
```

1.11.1 + patch (with address sanitization), three client addresses (ipv4 + ipv6 + ipv6):
```
   1000 CONNECT 192.168.1.22
   1125 CONNECT 6001:1234::1
     13 CONNECT 6001:1234::56d8:65b4:ff0f:0
    862 CONNECT 6001:1234::a:b:c:d
```

1.11.1 + patch (with address sanitization), four clients (2x ipv4, 2x ipv6):
```
   1000 CONNECT 127.0.0.1
   1000 CONNECT 192.168.1.22
    969 CONNECT 6001:1234::1
   1020 CONNECT 6001:1234::a:b:c:d
     11 CONNECT 6001:1234::b43c:b2f1:ff0f:0
```

So.. In all of these cases, the number of requests is correct and client requests with IPv4 addresses are handled correctly. But client requests with IPv6 addresses are handled incorrectly -- some requests are logged to some other IPv6 host (and also use that other host's address for ACL processing). And a small minority of IPv6 requests is seen as coming from a non-existent IPv6 address. (Address sanitization makes this clearly visible even though it didn't seem to detect anything).

**Comment by rofl0r** [comment] 2023-06-07 11:41
ok thanks for feedback. the patch is not necessary, i assumed it would pass a `char**` pointer when it should pass `char*` but i re-read the C spec and the existing code is correct too. since address sanitizer apparently doesn't shut down your program with detection of memory corruption, it appears the issue is not due to accessing non-initialized memory, but something else. i guess the best course of action to take to narrow down where the bug happens is git bisect.

**Comment by juhassi** [comment] 2023-06-07 12:22
Bisect says:

f6d4da5d81694721bf50b2275621e7ce84e6da30 is the first bad commit
commit f6d4da5d81694721bf50b2275621e7ce84e6da30
Author: rofl0r <retnyg@gmx.net>
Date:   Mon Dec 31 15:47:40 2018 +0000

    do hostname resolution only when it is absolutely necessary for ACL check

    tinyproxy used to do a full hostname resolution whenever a new client
    connection happened, which could cause very long delays (as reported in #198).

    there's only a single place/scenario that actually requires a hostname, and
    that is when an Allow/Deny rule exists for a hostname or domain, rather than
    a raw IP address. since it is very likely this feature is not very widely used,
    it makes absolute sense to only do the costly resolution when it is unavoidable.

 docs/man5/tinyproxy.conf.txt.in |  3 +++
 src/acl.c                       | 28 +++++++++++++++++++---------
 src/acl.h                       |  3 ++-
 src/child.c                     |  2 +-
 src/conns.c                     |  4 ----
 src/conns.h                     |  4 +---
 src/html-error.c                |  1 -
 src/reqs.c                      | 15 +++++++--------
 src/reqs.h                      |  3 ++-
 src/sock.c                      | 26 ++++----------------------
 src/sock.h                      |  2 +-
 11 files changed, 40 insertions(+), 51 deletions(-)

**Comment by juhassi** [comment] 2023-06-07 13:44
Can confirm: this fixes the issue. 👍

**Closed** 2023-06-07 18:57 UTC
