### ISSUE TITLE
IPv6 upstream

### ISSUE THREAD

**Issue by acetoneRu** [tinyproxy/tinyproxy#349] opened 2021-02-10 17:52 UTC
Hi. I can't add with correct behevior that line `upstream none "200::/7"`. It was not work absolutely or take all connections. How I can configure this?

**Comment by rofl0r** [comment] 2021-02-10 20:47
that's currently not implemented, though i think you could work around it by adding an /etc/hosts name for that ip and use the hostname in the config.

**Comment by acetoneRu** [comment] 2021-02-11 09:49
So I add line `200::0 ygg` to /etc/hosts and change tinproxy line to `upstream none "ygg/7"`. It doesn't work as well. Maybe because I use IPv6 subnet, not standalone host address.

**Comment by rofl0r** [comment] 2021-02-11 13:49
uhm, yeah. upstream needs to be a single ip. what did you expect it would do with a subnet ?

**Comment by acetoneRu** [comment] 2021-02-11 18:26
I need direct connection with IPv6 subnet (200::/7) without any proxy, but some addresses and domains I share to upstreams like Tor-socks. 

> upstream needs to be a single ip

Hmm.Realy? I using `upstream none "10.0.0.0/8"` and it's work! :)

**Comment by rofl0r** [comment] 2021-02-11 19:51
well, i meant the upstream proxy address, not the destination address.

**Comment by rofl0r** [comment] 2021-02-11 19:56
ok, so i overlooked from the beginning that you're trying to specify the target range, which should indeed work. so let's go back a step:

> It was not work absolutely or take all connections. How I can configure this?

so it works partially? what works, and what not ?

**Comment by acetoneRu** [comment] 2021-02-12 10:02
Good news if this should work!
So when I writing `upstream none "200::/7"` I have direct connection to that IPv6 network. But! But all traffic starts to go around Tor-proxy. 

Now my config looks like that:

    #upstream none "200::/7" # if uncommented, then all traffic (like IPv4 or IPv6 goes directly)
    upstream none "10.0.0.0/8"
    upstream socks5 127.0.0.1:9050 ".onion"
    upstream http   localv6:4444   ".i2p"
    upstream socks5 127.0.0.1:9050 # last point for tunneling all traffic

**Comment by rofl0r** [comment] 2021-02-12 14:34
is 200::/7 even  correct ipv6 ? if i recall correctly that means actually 0200:0000:....:0000/7, i.e. almost all ips in the entire 128 bit space (including the ipv4-in-ipv6 range)

**Comment by acetoneRu** [comment] 2021-02-12 16:19
Thank for answer again. Yep, `200::` also correctly like `::1` for example. "::" used instead of the longest zero sequence.
I tried using the full form of IPv6: `upstream none "0200:0000:0000:0000:0000:0000:0000:0000/7"`. The result is the same:( All traffic, including IPv6, goes bypassing Tor-upstream.

**Comment by rofl0r** [comment] 2021-02-12 16:40
well, isn't that exactly what it's supposed to do? unless it's an ipv6 that starts with e.f. 0xff

**Comment by acetoneRu** [comment] 2021-02-12 17:50
Every character in IPv6 displays 4 bits, two characters = 8 bits = 1 byte. Seven bit mask in "200::" admits IPv6 addresses with "0200:*" and "0300:*". So `200::/7` it's not standard for internet. This subnet used only in Yggdrasil meshnet. So... If upstream implemented correctly, opening regular sites with `upstream none "200::/7"` shouldn't be possible, because regular sites cannot have addresses on this subnet.

Hmm. For more understanding, I ran a test: writing random IPv6 subnet in `upstream` and always have one result: all traffic goes directly bypassing others upstream-rules! I think it's some bug in IPv6 upstream implementation.

**Comment by rofl0r** [comment] 2021-02-13 10:01
i just tried this out and i get: "WARNING   Feb 13 06:59:16.383 [5707]: line 6: Nonsense upstream rule: failed to parse netmask", that at least explains why all traffic goes through...

**Comment by rofl0r** [comment] 2021-02-13 10:14
alright, upon reading the code it turns out that the upstream code isn't ipv6 aware at all.
it uses its own parser, and i came across this once before and my plan is and was to use instead the parsing code of acl.c, however that requires some refactoring, and is not something to do before the final 1.11 release.

**Comment by rofl0r** [comment] 2021-02-13 15:20
@acetoneRu i implemented this in https://github.com/tinyproxy/tinyproxy/pull/350 .
it would be appreciated if you could try it out and provide feedback. optimally you could also test acl (allow/deny) statements, as that has been changed too.

**Comment by acetoneRu** [comment] 2021-02-15 10:46
Sorry for offline. I'm here. I going to compile frash code right now.

**Comment by acetoneRu** [comment] 2021-02-15 11:59
Yep. Now `upstream none "200::/7"` (also tested with full IPv6 form) is not allowed all traffic bypass another rules. But yes, it's also now worked correctly.
Thanks for your coding. I waiting implementation of that.

**Comment by rofl0r** [comment] 2021-02-15 13:10
> Now upstream none "200::/7" (also tested with full IPv6 form) is not allowed all traffic bypass another rules.

you mean it works ?


> But yes, it's also not worked correctly.

could you be more specific ?

> I waiting implementation of that.

that *is* the implementation. but this will have to wait till after the release before merging into master.

**Comment by acetoneRu** [comment] 2021-02-15 17:58
Please excuse my poor English. Apparently I was busy writing the answer. Instead of a normal test, I did a `git pull` on master and compile it. So after some fixes in master, IPv6 upstream not allowed all traffic bypass another rules, but I not testing implementation yet. Now I checking how I should do it.

**Comment by rofl0r** [comment] 2021-02-16 08:42
so you tested the PR now and it works as it should? great if so.
i'll leave this issue open anyhow until the PR is merged.

**Comment by acetoneRu** [comment] 2021-02-16 11:00
Yep. I tested PR and it works very fine!

**Comment by acetoneRu** [comment] 2021-07-10 15:41
Hi again. I upgraded to version 1.11.0 (used a trunk before). IPv6 upstream does not work again, as at the very beginning of this issue :)

**Comment by rofl0r** [comment] 2021-07-10 21:08
as stated before,

> however that requires some refactoring, and is not something to do before the final 1.11 release.

the fix you're after is in master though and will be included in next release. would of course be helpful if you could test whether master works as intended.

**Comment by acetoneRu** [comment] 2021-07-11 10:40
Tell me what tests and in what branches are required from me. I'm not a very experienced git user, so please attach links.

**Comment by rofl0r** [comment] 2021-07-11 12:56
`git clone https://github.com/tinyproxy/tinyproxy`

**Comment by acetoneRu** [comment] 2021-07-11 14:41
Yep. Works correctly!

**Comment by rofl0r** [comment] 2021-07-11 14:44
thanks for checking.

**Closed by rofl0r** 2021-07-11 14:44 UTC

**Comment by acetoneRu** [comment] 2021-07-11 14:51
Thanks for help and nice software!
