### ISSUE TITLE
Add support for PAC files using libproxy

### ISSUE THREAD

**Issue by Rhongomiant** [tinyproxy/tinyproxy#298] opened 2020-04-16 21:08 UTC
The upstream support is a great feature. However, it is limited in what it can do lacking support for wildcards, not supporting full URLs, ports, etc. There is already a system that allows for this, proxy auto configuration (PAC) and libproxy is designed to work with these files so you don't have to reinvent the wheel. While many web browsers and large scale applications support this, shell and other light applications lack support. Being able to setup a local simple HTTP, SOCKS, etc proxy that can forward "upstream" using PAC files would be very helpful. A specific example is running scripts using curl to pull data from an API. curl support HTTP and SOCKS proxies, but not PAC.

**Comment by rofl0r** [comment] 2020-09-05 19:01
duplicate of #224

**Closed by rofl0r** 2020-09-05 19:01 UTC
