### ISSUE TITLE
Tinyproxy unable to obtain the correct response cookie

### ISSUE THREAD

**Issue by DefeatAndVictory** [tinyproxy/tinyproxy#550] opened 2024-07-24 10:39 UTC
When using Tinyproxy to access a specific website at that time, the website had two response cookies, but Tinyproxy could only return one to me. I want to know what the problem is .The test website address is http://beijing.chinatax.gov.cn. Looking forward to your reply。

**Comment by rofl0r** [comment] 2024-07-24 11:54
duplicate of #403

**Closed by rofl0r** 2024-07-24 11:54 UTC

**Comment by DefeatAndVictory** [comment] 2024-07-25 05:17
I try to use 1.11.1-2 version ,but do not work . and i also use the lasted 1.11.2version ，do not work to ,only return one cookie . the website can return  two cookie 
Set-Cookie: acw_tc=3ccdc14f17218845587662038e5f83d2f44b732a2490187dce438c4e4546aa;path=/;HttpOnly;Max-Age=1800
Set-Cookie: VIP9lLgDcAL2S=60IA_zdO6PNu2tROHTDQZG1q_mlOJmUy95Qw90yRHbSDj7bJwq3truzoU63c58S1Laj8YlX0U.CgOFgrh9ixKjkG; Path=/; expires=Sun, 23 Jul 2034 05:15:58 GMT; HttpOnly
but only  return  the first

**Comment by rofl0r** [comment] 2024-07-25 09:01
i'm aware and this is a known issue. see the linked duplicate issue and the solution proposed there.

**Comment by DefeatAndVictory** [comment] 2024-07-25 09:18
I operated through the question link you provided, but it was not successful, such as version 1.11.1-2

**Comment by LauKr** [comment] 2024-07-25 14:53
Did you apply the commits manually and built a custom tinyproxy binary? This is not fixed in official releases yet.

**Comment by DefeatAndVictory** [comment] 2024-07-26 02:23
oh sorry，i just did it at https://github.com/rofl0r/tinyproxy.git branch 'setcookie_multi' ,it was succeful,thanks very much ! hope official  version can fix it soon.
