### ISSUE TITLE
tinyproxy support HTTP 1.1

### ISSUE THREAD

**Issue by alfador1** [tinyproxy/tinyproxy#311] opened 2020-08-11 11:57 UTC
Hello guys, I see tiny proxy tries to forward http 1.0
I need to connect through HTTP 1.1. Does it support it? I didn't see anything about the in the configuration.
If not, what would u advice to use as a forward proxy?

**Comment by rofl0r** [comment] 2020-08-11 12:54
please provide and explain examples that do not work correctly with tinyproxy's current way of doing things.

**Comment by alfador1** [comment] 2020-08-11 14:11
Providing example from the webserver receiving the requests : 
"GET /us-en/frontend-testing.html HTTP/1.1" 200 - This url is normal query uses http1.1

This happens when using the proxy
"GET /us-en/frontend-testing.html HTTP/1.0" 500

**Comment by rofl0r** [comment] 2020-08-11 14:58
duplicate of #152. i'll try to look into what it takes.

**Closed by rofl0r** 2020-08-11 14:58 UTC

**Comment by alfador1** [comment] 2020-08-11 15:00
@rofl0r  I saw this answer but recompiling is not an option for us

**Comment by rofl0r** [comment] 2020-08-11 15:38
i opened a PR addressing this issue: https://github.com/tinyproxy/tinyproxy/pull/312

please report whether it resolves it.

**Comment by alfador1** [comment] 2020-08-11 17:33
Sorry for stupid question I installed it through apt , not sure how to test the PR? Especially through make install

**Comment by rofl0r** [comment] 2020-08-11 18:37
```
git clone git://github.com/rofl0r/tinyproxy
cd tinyproxy
git checkout support_http_11
autoreconf -i
./configure --prefix=/usr
make -j4
```

after `make` build might fail due to issues with manpage generation, but you will find in src/ a tinyproxy binary anyway which you could manually copy to /usr/bin/ or run it from there to see whether it fixes the issues.

**Comment by alfador1** [comment] 2020-08-11 18:41
What about tinyproxy conf. How to attach it?

**Comment by rofl0r** [comment] 2020-08-11 21:25
if the config is in /etc/tinyproxy.conf it will be picked up automatically. nothing really different.
but you can specify absolute path to the config file on the command line e.g. `src/tinyproxy -c path/to/foo.conf`

**Comment by alfador1** [comment] 2020-08-12 07:15
It works I confirm ! :)

**Comment by alfador1** [comment] 2020-08-12 07:27
When will it be merged and what will be the procedure to install that from
APT repository?

**Comment by rofl0r** [comment] 2020-08-12 13:59
> It works I confirm ! :)

that's great, thanks. could you test it a little longer so we can see it doesn't have undesired side effects in other cases ?

> When will it be merged and what will be the procedure to install that from APT repository?

after some more testing. don't count on that it will be available anytime soon in APT repositories, as debian managers are quite slow in upgrading their packages.
