### ISSUE TITLE
Specifying multiple proxies for the same upstream?

### ISSUE THREAD

**Issue by fgimian** [tinyproxy/tinyproxy#295] opened 2020-03-22 01:18 UTC
Hey again,

It doesn't seem to be currently possible to specify multiple proxies for the same hostname where the first proxy would be attempted first and if it fails, tinyproxy would fall back to the second proxy.

This would be similar to PAC files where you can return multiple proxies for a domain:

e.g.

```javascript
return "PROXY 4.5.6.7:8080; PROXY 7.8.9.10:8080";
```

Huge thanks
Fotis

**Comment by rofl0r** [comment] 2020-03-29 11:29
duplicate of https://github.com/tinyproxy/tinyproxy/issues/208

**Closed by rofl0r** 2020-03-29 11:29 UTC
