### ISSUE TITLE
tinyproxy with upstream ipv6 ip/bits is not working

### ISSUE THREAD

**Issue by wheldom01** [tinyproxy/tinyproxy#393] opened 2021-08-10 11:25 UTC
Using tinyproxy 1.11.0 stable and configuring a upstream for traffic destined for a ipv6 ip/bits target. Traffic is not forwarded to the Upstream proxy as expected.

2021-08-10T10:32:23.175+01:00 | INFO Aug 10 10:32:23 [1]: Initializing tinyproxy ...
2021-08-10T10:32:23.175+01:00 | INFO Aug 10 10:32:23 [1]: Reloading config file
2021-08-10T10:32:23.175+01:00 | INFO Aug 10 10:32:23 [1]: Added upstream http 172.25.15.251:8080 for fdcd:c8d9:4747:1::100
2021-08-10T10:32:23.175+01:00 | INFO Aug 10 10:32:23 [1]: Added upstream http 172.25.15.251:8080 for fdcd:c8d9:4747:1::101
2021-08-10T10:32:23.175+01:00 | INFO Aug 10 10:32:23 [1]: Added upstream http 172.25.15.251:8080 for fd8d:6500::/24

2021-08-10T11:46:33.658+01:00 | INFO Aug 10 10:46:33 [107]: No upstream proxy for fd8d:6500:24fc:f300::1
2021-08-10T11:46:33.658+01:00 | INFO Aug 10 10:46:33 [107]: opensock: opening connection to fd8d:6500:24fc:f300::1:80
2021-08-10T11:46:33.658+01:00 | INFO Aug 10 10:46:33 [107]: opensock: getaddrinfo returned for fd8d:6500:24fc:f300::1:80
2021-08-10T11:46:33.658+01:00 | ERROR Aug 10 10:46:33 [107]: opensock: Could not establish a connection to d8d:6500:24fc:f300::1

Forwarding to a ipv6 address works as expected.

**Comment by rofl0r** [comment] 2021-08-10 14:20
duplicate of #349 (resolved in master).

**Closed by rofl0r** 2021-08-10 14:20 UTC
