### ISSUE TITLE
Slow connections; latest version not in repo

### ISSUE THREAD

**Issue by keunes** [tinyproxy/tinyproxy#401] opened 2021-10-05 07:13 UTC
Hello,

I'm using tinyproxy 1.10.0-2+deb10u1 on my RaspberryPi with Raspbian 10 (buster). I installed tinyproxy via the default repo, but I have an issue that connections are super slow, despite superspeedy internet connections.

Now I saw this notification:

> # IMPORTANT NOTICE
> 
> Before filing an issue here PLEASE keep in mind that **tinyproxy 1.10.0 and older are no longer supported**.
> Do not report issues with 1.10.0 or older, first try latest release 1.11.0, or even better, git master, and see whether the issue is already fixed.

However, 1.11 is not in the Raspbian repository. So my question is: would you know if/how we can get the latest version in the repo?

Many thanks for working on tinyproxy!

**Comment by rofl0r** [comment] 2021-10-05 10:07
please talk with raspbian maintainers to have the package updated. meanwhile you can always compile tinyproxy from source. the slowness you refer to is most likely caused by the issue fixed with commit f6d4da5d81694721bf50b2275621e7ce84e6da30 (3 years ago).

**Closed by rofl0r** 2021-10-05 10:07 UTC
