### ISSUE TITLE
How to set upstream-proxy with  https-transparent mode

### ISSUE THREAD

**Issue by Totti0135** [tinyproxy/tinyproxy#154] opened 2018-03-13 15:34 UTC
I want to let the tinyproxy as a https-transparent proxy and set another upstream-proxy.

**Comment by rofl0r** [comment] 2018-03-13 19:33
duplicate of https://github.com/tinyproxy/tinyproxy/issues/88

**Closed by rofl0r** 2018-03-13 19:33 UTC
