### ISSUE TITLE
Tinyproxy not forwarding client headers to remote machine

### ISSUE THREAD

**Issue by harvetech** [tinyproxy/tinyproxy#485] opened 2023-03-12 13:47 UTC
## Tinyproxy version
[1.11.1-r2 ](https://pkgs.alpinelinux.org/flag/main/tinyproxy/1.11.1-r2)

## Issue

I am using tinnyproxy inside my docker container. I want to forward all of the client headers and don't want to filter for any. But the logs always say, 
` client headers are not forwarded to the remote address.`

I have disabled the via headers. I want my proxy to be in stealth mode so the remote machine doesn't know that the request is coming from a proxy. All I need is the change of IP address everything else should be forwarded from the client.  Which settings should I change to force it to forward the client headers and not add any further headers into it ?

Best Regards

**Comment by rofl0r** [comment] 2023-03-13 12:28
duplicate of #469

**Closed by rofl0r** 2023-03-13 12:28 UTC
