### ISSUE TITLE
Makefile error

### ISSUE THREAD

**Issue by ddatsh** [tinyproxy/tinyproxy#84] opened 2017-03-27 02:49 UTC
```
make  all-recursive
make[1]: Entering directory `/tmp/tinyproxy'
Making all in src
make[2]: Entering directory `/tmp/tinyproxy/src'
Makefile:670: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.
make[2]: Leaving directory `/tmp/tinyproxy/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/tmp/tinyproxy'
make: *** [all] Error 2
```

**Comment by rofl0r** [comment] 2017-03-27 02:52
duplicate of https://github.com/tinyproxy/tinyproxy/issues/72

**Closed** 2017-03-27 02:58 UTC
