### ISSUE TITLE
ALNUM for basicauth is restrictive

### ISSUE THREAD

**Issue by pierredavidbelanger** [tinyproxy/tinyproxy#271] opened 2019-10-25 21:14 UTC
Here [in conf.c](https://github.com/tinyproxy/tinyproxy/blob/master/src/conf.c#L237):
```
STDCONF ("basicauth", ALNUM WS ALNUM, handle_basicauth),
```

The parser expect username and password to be `ALNUM`. I find this a little restrictive, given that we all know the more complex a password is, the more secure it is. (I know basic auth is no more that clear text, but lets say everything is behind an SSL terminating proxy).

I wonder if it would be too complex to expect `STR` instead ? And if this change would be back compatible ?

I am willing to send a PR if you are interested.

**Comment by davidebeatrici** [comment] 2019-11-18 07:44
I agree, special characters should be allowed.

**Comment by rofl0r** [comment] 2019-11-18 16:54
i don't see this as a problem, tbh.
here's an example password using the allowed set `y64IwyxqFRovRGZC`, which is impossible to crack. using STR is certainly not the right "fix", as it requires a term enclosed in double quotes. the spec isn't entirely clear on what should be allowed or not, but from what i can tell it should be "ascii printable" without `:` for the username, and "ascii printable" for the password.

**Comment by pierredavidbelanger** [comment] 2019-11-18 17:02
@rofl0r I agree it should be "ascii printable". But right now, its even a smaller subset of "ascii printable": `ALNUM` is defined as `"([-a-z0-9._]+)"`

Anyways, if it is decided not to fix this one, I do not really care, since I already changed my scripts to generate an `ALNUM` compatible password.

**Comment by rofl0r** [comment] 2019-11-18 17:08
> But right now, its even a smaller subset of "ascii printable": ALNUM is defined as "([-a-z0-9._]+)"

yeah, i'm aware what alnum means. :)

**Comment by davidebeatrici** [comment] 2019-11-18 19:06
To be clear, with "special characters" I meant characters other than digits and A to Z letters in the ASCII charset.

For example, `6=~_-vuA` can be used as password with Squid, but not with tinyproxy.

From https://tools.ietf.org/html/rfc7617#section-3:
> User-ids or passwords containing characters outside the US-ASCII character repertoire will cause interoperability issues, unless both communication partners agree on what character encoding scheme is to be used.  Servers can use the new 'charset' parameter ([Section 2.1](https://tools.ietf.org/html/rfc7617#section-2.1)) to indicate a preference of "UTF-8", increasing the probability that clients will switch to that encoding.
>
> The 'realm' parameter carries data that can be considered textual; however, [[RFC7235](https://tools.ietf.org/html/rfc7235)] does not define a way to reliably transport non-US-ASCII characters.  This is a known issue that would need to be addressed in a revision to that specification.

**Comment by rofl0r** [comment] 2020-09-06 23:09
PR welcome, should be easy to model with the changes from this commit dc41b3533326d745c65afaea4cb34c229a31d0c3 (note the commit message is wrong, the commit is about upstream, not basic auth).
i'm just not doing it myself because i don't have time to test it.

**Comment by rofl0r** [comment] 2020-09-06 23:51
actually there's already a PR addressing this that needs testing: https://github.com/tinyproxy/tinyproxy/pull/230

**Comment by rofl0r** [comment] 2020-09-06 23:53
...and actually this is a duplicate of #229 . please move further discussion of interested parties there.

**Closed by rofl0r** 2020-09-06 23:53 UTC
Labels: enhancement, help wanted
