### ISSUE TITLE
mystery segfault in pidfile_create under cygwin

### ISSUE THREAD

**Issue by guineawheek** [tinyproxy/tinyproxy#11] opened 2016-01-19 03:27 UTC
In `pidfile_create`, a compiled cygwin tinyproxy often segfaults when trying to fprintf the pid to the file handle. I don't know _why_ this happens but I do know that disabling that code makes tinyproxy run normally otherwise.

**Comment by rofl0r** [comment] 2020-09-07 17:18
please test whether the issue is fixed with current master.

**Comment by ianmarcinkowski** [comment] 2023-10-11 14:50
Probably reasonable to close, as it is so old.

Hey, I hope it's not annoying, but I'm going to go through a few of the oldest issues and comment on them if they seem reasonable to close.  As a user, it's hard to see 100 open issues in a small project.  Please let me know if this is annoying :)

**Closed** 2023-10-11 22:42 UTC
