### ISSUE TITLE
Whether the tinyproxy  should force response HTTP/1.0

### ISSUE THREAD

**Issue by phpor** [tinyproxy/tinyproxy#42] opened 2016-11-05 15:49 UTC
First, please forgive my English is very poor.

I found that tinyproxy always send HTTP/1.0 to upstream，but upstream server not always reponse HTTP/1.0， when upstream server reponse HTTP/1.1, then tinyproxy transfer HTTP/1.1 to client，and removed connection header，if the client is curl， it will show warnning like：

no chunk, no close, no size. Assume close to signal end

So， whether the tinyproxy  should force response HTTP/1.0 ?

like this： in function static int process_server_headers (struct conn_s *connptr)
`
        // Add the following three lines
        if (response_line[7] == '1') {
                response_line[7] = '0';
        }
        /* Send the saved response line first */
        ret = write_message (connptr->client_fd, "%s\r\n", response_line);
`

**Comment by rofl0r** [comment] 2020-09-07 17:53
duplicate of #152 

could you test my PR #312 please ?

**Closed by rofl0r** 2020-09-07 17:53 UTC
Labels: duplicate
