### ISSUE TITLE
Tinyproxy stops responding on FreeBSD

### ISSUE THREAD

**Issue by jasonemann** [tinyproxy/tinyproxy#25] opened 2016-07-13 14:37 UTC
I have been working on updating Tinyproxy in FreeBSD's ports collection from 1.8.3 to 1.8.4, but in the course of testing the newer version I have been encountering problems.

The new port version builds OK and Tinyproxy starts up and correctly listens on multiple specified interfaces, as fixed in 1.8.4, but after several hours of running, although still accepting client connections, it stops responding to requests.  At this point, it takes a restart to get it working again.

I have updated the port to use the source tree on Github under the 1.8.4 tag, instead of the tarball from https://download.banu.com/tinyproxy/1.8/tinyproxy-1.8.3.tar.gz and have updated a few of the port's patches to account for the differences in the source files.  See https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=207051 for details.

Would the developer be able to advise on how to diagnose this problem?  I'm happy to gather any diagnostic information or perform any testing necessary.

**Comment by rofl0r** [comment] 2016-07-13 19:47
you could build it with debug info, and when it reacts no longer attach to the process with gdb and look (with `bt` - backtrace) where it's hanging.

**Comment by rofl0r** [comment] 2016-07-15 08:56
oh, i forgot to say that after you attach gdb to the process you need to hit CTRL-C before you can enter the bt command.

**Comment by obnoxxx** [comment] 2016-08-25 21:02
Additional possibilities:
- set LogLevel to Info and then inspect the logs
- run tinyproxy under valgrind

**Comment by obnoxxx** [comment] 2016-09-10 20:55
I would like to help here, but logs would help.

**Comment by dmz-uk** [comment] 2016-09-26 10:11
I've also been seeing the issue with the 1.8.4 stopping responding overnight under EL6/EL7. Some investigation shows that it's triggered by SIGHUP reload (logrotate in this case). tinyproxy 1.8,4 is not respawning its children after reload and the parent process is sitting in child_main_loop() with nothing to handle requests. Requests coming in lead to errors in the logs "error calling select: Interrupted system call".

**Comment by jasonemann** [comment] 2016-09-26 10:28
Sorry for going quiet on this for so long.  Hope to have some time to do some testing soon.

**Comment by dmz-uk** [comment] 2016-09-26 10:58
Okay, here's the bug (child.c:234), the children are being signalled to reload, but this is causing them to exit(1) due to the signal interrupting the blocking select() call:

                ret = select(maxfd + 1, &rfds, NULL, NULL, NULL);
                if (ret == -1) {
                        log_message (LOG_ERR, "error calling select: %s",
                                     strerror(errno));
                        exit(1);
                }

**Comment by hdeadman** [comment] 2016-12-22 15:19
I found this issue by after googling "tinyproxy stops working overnight", and I can confirm that I recently started running logrotate on the server running tinyproxy. (I am on RedHat EL7). I suppose the fix is to change the tinyproxy logrotate config to restart the tinyproxy service?

**Comment by dmz-uk** [comment] 2016-12-22 17:33
You should be free to handle SIGHUP however you want, it's a convenience that most daemons will do a config reload and close/reopen of log files. From my reading of the unmodified tinyproxy code, there's no handling of the child count by the parent when they exit on SIGHUP, leading to the parent process sitting there with no children to service requests, so either way it's an error?

**Comment by dmz-uk** [comment] 2016-12-22 17:48
FYI we fixed tinyproxy behaviour with logrotate back in September by just ignoring the exit in the child on SIGHUP. It's debatable whether this is correct/intended behaviour, but as a stopgap "works for us". I've since also seen the same behaviour crop up on 1.8.3, too (presumably as an edge case):

[tinyproxy-1.8.4-no-sig-exit.patch.txt](https://github.com/tinyproxy/tinyproxy/files/669427/tinyproxy-1.8.4-no-sig-exit.patch.txt)

**Comment by rofl0r** [comment] 2016-12-22 17:49
can you open a PR with your change, please ?

**Comment by dmz-uk** [comment] 2016-12-22 17:55
Okay, #67

**Comment by hdeadman** [comment] 2016-12-22 18:40
EPEL 7 is still distributing 1.8.3 which is where I am seeing the problem. I don't see the logrotate config for tinyproxy in this repo so I assume the EPEL packager is adding that downstream? It may be a bug for them since the logrotate postrotate config is signaling tinyproxy in a way that breaks tinyproxy. Not sure where to report that b/c even if it gets fixed here, we would want them to backport that fix.

**Comment by rofl0r** [comment] 2016-12-22 19:45
it's probably a bug anyway to just kill the child process, but leave the parent process running.
but yeah, it's not nice to send SIGHUP to processes that are not prepared for it.

**Comment by rofl0r** [comment] 2020-09-07 18:02
this was fixed by #67, and now obsolete since b935dc85c3fca51de8e131d6aa2047f8a0404f0c

**Closed by rofl0r** 2020-09-07 18:02 UTC
Labels: possible bug
