### ISSUE TITLE
upstream syntax error

### ISSUE THREAD

**Issue by VantaxDev** [tinyproxy/tinyproxy#456] opened 2022-09-06 14:41 UTC
```
$ tinyproxy -v
tinyproxy 1.11.0-rc1-65-git-84f203f
```

compiled with

```
./configure --enable-upstream -enable-transparent --enable-reverse --enable-debug --enable-xtinyproxy --enable-filter
```

in .conf this creates an error ( without credentials is fine but I need credentials ( alphanumeric chars ))

```
upstream http aaa:bbb@22.222.2.3:111

```

```
Sep 06 14:40:00 aws_d tinyproxy[12630]: Unable to parse config file. Not starting.
Sep 06 14:40:00 aws_d tinyproxy[12630]: Syntax error on line 331
Sep 06 14:40:00 aws_d systemd[1]: tinyproxy.service: control process exited, code=exited status=70
Sep 06 14:40:00 aws_d systemd[1]: Failed to start Startup script for the tinyproxy server.
-- Subject: Unit tinyproxy.service has failed

```

Any suggestions ?

**Comment by rofl0r** [comment] 2022-09-06 21:27
works for me. does your username or password contain special characters like `:` or `@` ?

**Comment by VantaxDev** [comment] 2022-09-06 21:32
No, I've triple checked that.

I installed tinyproxy in an ubuntu virtualmachine and it worked ( 1.10 )
the same config line on my AWS machine ( ami linux ) give me "syntax error".



```
$ tinyproxy -t
tinyproxy: invalid option -- 't'
Usage: tinyproxy [options]

Options are:
  -d        Do not daemonize (run in foreground).
  -c FILE   Use an alternate configuration file.
  -h        Display this usage information.
  -v        Display version information.

Features compiled in:
    XTinyproxy header
    Filtering
    Transparent proxy support
    Reverse proxy support
    Upstream proxy support


```


seems that upstream is supported...

not sure what else I can check

**Comment by rofl0r** [comment] 2022-09-07 00:28
i tried this config for the "upstream" proxy:

```
Port 8188
Timeout 600
MaxClients 128
BasicAuth user passw
```

and this one for the one connecting to that upstream:

```
Port 8881
Timeout 600
MaxClients 128
upstream http user:passw@127.0.0.1:8188
```

both configs get properly processed. maybe the config error you're getting is from some unrelated line. start small with the configs i pasted then scale up to what you're using to figure out what's going wrong.

**Comment by VantaxDev** [comment] 2022-09-07 07:52
I cloned with SCP the same file that works on my ubuntu virtual machine with tinyproxy 1.10 and on AMI linux I got "syntax error"

I've switched to squid but if you tell me another tests I can do another couple of test to help you debug that.

IMHO is something on the OS that is missing and the upstream user:pass is not recognized.

if I remote user:pass@ the upstream support works fine.

best regards

**Comment by VantaxDev** [comment] 2022-09-07 16:21
Hi,
I'm not lazy, I'm busy, but I would like to help you fixing that

```
sudo tinyproxy -d -c /etc/tinyproxy/tinyproxy.conf 
Syntax error on line 329
Unable to parse config file. Not starting.

```

and the file is the default one with just one row added

https://pastebin.com/YPeGFrZP





IMHO is something in AMI linux that makes the upstream module crazy

if i remove the credentials

https://pastebin.com/mykA64zp

it starts

best regards

**Comment by rofl0r** [comment] 2022-09-07 19:46
alright, i just tested this on ubuntu using glibc, like ami linux, and it works there - so the problem is definitely with the libc version used on AMI linux.
if you want to get this fixed then you gotta report them that the posix regex implementation in their libc version is broken.
closing this as "not our bug".

**Closed by rofl0r** 2022-09-07 19:46 UTC
