### ISSUE TITLE
Tinyproxy is not starting automatically during boot of the server

### ISSUE THREAD

**Issue by pistik1980** [tinyproxy/tinyproxy#554] opened 2024-09-06 11:46 UTC
**Description:** 
When tinyproxy has been configured with "Listen" option, Tinyproxy won't start automatically during boot of the server with error message "/usr/bin/tinyproxy: Could not create listening sockets.". Once server has started, tinyproxy was able to start via systemctl start tinyproxy.service without any problems.

**Tinyproxy version:** 1.11.2
**OS version:** Red Hat Enterprise Linux release 8.10 (Ootpa)
**Tinyproxy configuration `/etc/tinyproxy/tinyproxy.conf:`**
```
User tinyproxy
Group tinyproxy
Port 8080
Listen <IP>
Bind <IP>
Timeout 600
DefaultErrorFile "/usr/share/tinyproxy/default.html"
StatFile "/usr/share/tinyproxy/stats.html"
LogFile "/var/log/tinyproxy/tinyproxy.log"
LogLevel Info
MaxClients 100
ViaProxyName "tinyproxy"
Filter "/etc/tinyproxy/filter"
FilterType fnmatch
FilterCaseSensitive On
FilterDefaultDeny Yes
```

**Solution:**
Tinyproxy has been starting during network.target level and couldn't allocate port. My workaround was to change target level to network-online.target as you can see below. 

`/usr/lib/systemd/system/tinyproxy.service` 
```
[Unit]
Description=small, efficient HTTP/SSL proxy daemon
Documentation=man:tinyproxy(8)
#After=network.target
After=network-online.target

[Service]
Type=exec
ExecStart=/usr/bin/tinyproxy -d
ExecReload=/usr/bin/kill -USR1 $MAINPID

[Install]
WantedBy=multi-user.target
```

**Comment by rofl0r** [comment] 2024-09-07 12:51
duplicate of #553 - you gotta take this to the maintainer of your distro package.

**Closed by rofl0r** 2024-09-07 12:51 UTC
